/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'checkTripExists' : IDL.Func([], [IDL.Bool], ['query']),
  'getCost' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Nat], ['query']),
  'getDistance' : IDL.Func([], [IDL.Float64], []),
  'getFinalTripStep' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTime' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'startBooking' : IDL.Func([], [IDL.Nat], []),
  'verifyOTP' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'checkTripExists' : IDL.Func([], [IDL.Bool], ['query']),
    'getCost' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Nat], ['query']),
    'getDistance' : IDL.Func([], [IDL.Float64], []),
    'getFinalTripStep' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTime' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'startBooking' : IDL.Func([], [IDL.Nat], []),
    'verifyOTP' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };